// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

//project.js

export const FETCH_PROJECT = 'FETCH_PROJECT'
export const FETCH_RESOURCES = 'FETCH_RESOURCES'
export const UPDATE_RESOURCES = 'UPDATE_RESOURCES'
export const UPLOAD_RESOURCE = 'UPLOAD_RESOURCE'

export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS'
export const FETCH_PROJECT_FAILED = 'FETCH_PROJECT_FAILED'

export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS'
export const UPLOAD_RESOURCE_SUCCESS = 'UPLOAD_RESOURCE_SUCCESS'
export const UPLOAD_RESOURCE_FAILED = 'UPLOAD_RESOURCE_FAILED'

export const FETCH_RESOURCES_FAILED = 'FETCH_RESOURCES_FAILED'
//submit_question.js
export const SAVE_QUOTE_TEMP = "SAVE_QUOTE_TEMP"

//myquestions.js
export const FETCH_QUESTIONS = "FETCH_QUESTIONS"
export const FETCH_QUESTIONS_FAILED = "FETCH_QUESTIONS_FAILED"
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS"

//expert.js
export const BECAME_EXPERT = "BECAME_EXPERT"



// lang.js
export const SET_LOCALE = 'SET_LOCALE'
